# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wriftai < Formula
  desc "Command-line interface for WriftAI"
  homepage "https://github.com/wriftai/cli"
  version "0.57.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wriftai/cli/releases/download/v0.57.0/wriftai_Darwin_x86_64.tar.gz"
      sha256 "62a0a263b3475ee3d7f7286eaec8f85d771bab860ed0c9fa92512c0bee0a9d6d"

      define_method(:install) do
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wriftai/cli/releases/download/v0.57.0/wriftai_Darwin_arm64.tar.gz"
      sha256 "7464fec3fb82450b96eda1d09da1cc4a580159464059874c1ace052e600ab387"

      define_method(:install) do
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wriftai/cli/releases/download/v0.57.0/wriftai_Linux_x86_64.tar.gz"
      sha256 "2d3d6f346f38f227a72684d0d025b1110a79747afee579699b888c18ffe2f975"
      define_method(:install) do
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
        man1.install Dir["man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wriftai/cli/releases/download/v0.57.0/wriftai_Linux_arm64.tar.gz"
      sha256 "1a8b648912102da30747f4f2483cedb41df3da87395cbe0089ad04399017e571"
      define_method(:install) do
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
        man1.install Dir["man/*.1"]
      end
    end
  end

  test do
    output = shell_output("#{bin}/wriftai version")
    assert_match version.to_s, output
  end
end
