# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wriftai < Formula
  desc "Command-line interface for WriftAI"
  homepage "https://github.com/wriftai/cli"
  version "0.19.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wriftai/cli/releases/download/v0.19.0/wriftai_Darwin_x86_64.tar.gz"
      sha256 "54cbea767359b2a9e40492e5fb540b32d4e797f543141a351ad93a7854b59b3e"

      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wriftai/cli/releases/download/v0.19.0/wriftai_Darwin_arm64.tar.gz"
      sha256 "46d073f64b3013ded5dd9d3880a2edc3939f0b096e53274777d58baeeb948dc6"

      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wriftai/cli/releases/download/v0.19.0/wriftai_Linux_x86_64.tar.gz"
      sha256 "c836398c670032a6c2dc5b527b21de92bba72b67eae58ab65f93f05e63ec9e89"
      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wriftai/cli/releases/download/v0.19.0/wriftai_Linux_arm64.tar.gz"
      sha256 "4b3c1a97104310ffc888a82103c4b837a7773357147ddd682bc61b5f1bb76970"
      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
  end

  test do
    output = shell_output("#{bin}/wriftai version")
    assert_match version.to_s, output
  end
end
