# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wriftai < Formula
  desc "Command-line interface for WriftAI"
  homepage "https://github.com/wriftai/cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wriftai/cli/releases/download/v0.1.1/wriftai_Darwin_x86_64.tar.gz"
      sha256 "a39f004c6e93f8d55e30c78b15ad662a9a1c85d6e582badab94582594385ac6e"

      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wriftai/cli/releases/download/v0.1.1/wriftai_Darwin_arm64.tar.gz"
      sha256 "70b4efcb7d129f6dcbe818dcf7e0ff2ca565b47470e555f77a078dc8470ad6f5"

      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wriftai/cli/releases/download/v0.1.1/wriftai_Linux_x86_64.tar.gz"
      sha256 "95abab9d446ed4a2b108a36aa312122a25b4d4b6ee231254c48e67440723baf3"
      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wriftai/cli/releases/download/v0.1.1/wriftai_Linux_arm64.tar.gz"
      sha256 "27db5939a41e25050ec8a4920e18fed02d1c9bed15297c725faf903b35dcefde"
      def install
        bin.install "wriftai"

        bash_completion.install "completions/wriftai.bash" => "wriftai"
        zsh_completion.install "completions/_wriftai"
        fish_completion.install "completions/wriftai.fish"
      end
    end
  end

  test do
    output = shell_output("#{bin}/wriftai version")
    assert_match version.to_s, output
  end
end
